import Head from "next/head";
import { useQuery } from "@tanstack/react-query";

export default function RESTFilms() {
  // Query Function
  const getFilms = async () => {
    try {
      const response = await fetch("https://swapi.dev/api/films");
      // fetch does not throw errors by default
      if (!response.ok) {
        throw new Error("Network response was not ok");
      }
      const data = await response.json();
      return data;
    } catch (error) {
      // Must throw an error to trigger the error state in React Query
      throw new Error("Error fetching data");
    }
  };

  // React Query for RESTful Request
  const { isPending, isError, data, error } = useQuery({
    queryKey: ["RESTFilms"],
    queryFn: getFilms,
  });

  if (isPending) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error.message}</span>;
  }

  return (
    <>
      <Head>
        <title>React Query for RESTful Request</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>React Query for RESTful Request</h1>
      <ul>
        {data?.results.map((film: { title: string }) => (
          <li key={film.title}>{film.title}</li>
        ))}
      </ul>
    </>
  );
}
